name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: LLM Provider(s) Affected
      multiple: true
      options:
        - OpenAI
        - Google Gemini
        - Anthropic Claude
        - xAI Grok
        - Not provider-specific

  - type: input
    id: env
    attributes:
      label: OS / Browser
      placeholder: "e.g. Windows 11 / Chrome 125"

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Screenshots
      description: Paste Flask console output or browser DevTools errors here
